export const MANUFACTURERS = [
  "FortiGate",
  "FortiSIEM",
  "FortiWeb",
  "Trend Vision One",
  "Microsoft IIS",
  "VMware",
  "Wazuh",
  "Sysmon",
  "Windows Security",
  "Active Directory",
  "Linux Auditd",
  "Apache",
  "Nginx",
  "SSH",
  "VPN",
  "DNS",
  "DHCP",
  "Firewall",
  "Suricata",
  "Zeek",
  "pfSense",
  "Cisco ASA",
  "Cisco IOS",
  "Mikrotik",
  "AWS CloudTrail",
  "Azure",
  "Microsoft Defender",
  "Office 365",
  "Exchange",
  "Kubernetes",
  "Docker",
  "PostgreSQL",
  "MySQL"
] as const;

export const EVENT_TYPES = [
  "Rotina SOC N1 - Mix diário",
  "Logon",
  "Logoff",
  "Falha de autenticação",
  "Movimentação lateral",
  "RDP",
  "PowerShell",
  "CMD",
  "Linux Bash",
  "Criação de processos",
  "Execução remota",
  "Criação de usuários",
  "Alteração de grupos",
  "Dump de credenciais",
  "Mimikatz",
  "Pass-the-Hash",
  "Kerberoasting",
  "Golden Ticket",
  "DNS Tunneling",
  "Beacon C2",
  "Reverse Shell",
  "Web Shell",
  "SQL Injection",
  "XSS",
  "Directory Traversal",
  "Brute Force",
  "Port Scan",
  "Nmap",
  "Masscan",
  "Hydra",
  "FTP",
  "SMTP",
  "SMB",
  "LDAP",
  "HTTP",
  "HTTPS",
  "VPN",
  "Ransomware",
  "Exfiltração",
  "Malware",
  "Botnet",
  "APT",
  "Insider Threat",
  "FortiGate Traffic Forward",
  "FortiGate App Control",
  "FortiGate IPS",
  "FortiGate Config Change",
  "FortiWeb HTTPS",
  "Windows 4624 - Logon bem-sucedido",
  "Windows 4625 - Falha de logon",
  "Windows 4771 - Falha Kerberos",
  "Windows 5145 - Acesso SMB",
  "Windows 4724 - Redefinição de senha",
  "Windows 4728 - Membro adicionado a grupo",
  "Windows 4735 - Grupo alterado",
  "Windows 4738 - Conta de usuário alterada",
  "Windows 5038 - Falha de integridade",
  "Windows 1511 - Perfil temporário",
  "IIS 401 - Não autorizado",
  "Linux Auditd - Execução de processo",
  "Linux Auditd - Base64",
  "Linux Auditd - Comando who",
  "VMware - Utilização de interface",
  "Trend Vision One - Arquivo via SMB",
  "Trend Vision One - SELinux desabilitado"
] as const;

export const GENERATION_PROFILES = [
  "Rotina SOC N1",
  "Autenticação Windows",
  "Perímetro Fortinet",
  "Servidores Linux",
  "Aplicações Web",
  "Genérico"
] as const;

export const REALISM_LEVELS = ["operacional", "laboratório", "simplificado"] as const;

export const SEVERITIES = ["informational", "low", "medium", "high", "critical"] as const;

export const EXPORT_FORMATS = ["txt", "json", "csv", "syslog", "cef", "leef", "evtx", "ndjson"] as const;

export const SIMULATION_MODES = [
  "Blue Team",
  "SOC",
  "Purple Team",
  "Threat Hunting",
  "CTF",
  "Empresa pequena",
  "Empresa média",
  "Banco",
  "Hospital",
  "Universidade",
  "Indústria",
  "Cloud",
  "Ransomware",
  "APT",
  "Insider Threat"
] as const;

export const COMPANY_TYPES = [
  "Empresa pequena",
  "Empresa média",
  "Banco",
  "Hospital",
  "Universidade",
  "Indústria",
  "SaaS",
  "E-commerce",
  "Governo",
  "Cloud first"
] as const;
