export const MANUFACTURERS = [
  "FortiGate",
  "FortiSIEM",
  "Wazuh",
  "Sysmon",
  "Windows Security",
  "Active Directory",
  "Linux Auditd",
  "Apache",
  "Nginx",
  "SSH",
  "VPN",
  "DNS",
  "DHCP",
  "Firewall",
  "Suricata",
  "Zeek",
  "pfSense",
  "Cisco ASA",
  "Cisco IOS",
  "Mikrotik",
  "AWS CloudTrail",
  "Azure",
  "Microsoft Defender",
  "Office 365",
  "Exchange",
  "Kubernetes",
  "Docker",
  "PostgreSQL",
  "MySQL"
] as const;

export const EVENT_TYPES = [
  "Logon",
  "Logoff",
  "Falha de autenticação",
  "Movimentação lateral",
  "RDP",
  "PowerShell",
  "CMD",
  "Linux Bash",
  "Criação de processos",
  "Execução remota",
  "Criação de usuários",
  "Alteração de grupos",
  "Dump de credenciais",
  "Mimikatz",
  "Pass-the-Hash",
  "Kerberoasting",
  "Golden Ticket",
  "DNS Tunneling",
  "Beacon C2",
  "Reverse Shell",
  "Web Shell",
  "SQL Injection",
  "XSS",
  "Directory Traversal",
  "Brute Force",
  "Port Scan",
  "Nmap",
  "Masscan",
  "Hydra",
  "FTP",
  "SMTP",
  "SMB",
  "LDAP",
  "HTTP",
  "HTTPS",
  "VPN",
  "Ransomware",
  "Exfiltração",
  "Malware",
  "Botnet",
  "APT",
  "Insider Threat"
] as const;

export const SEVERITIES = ["informational", "low", "medium", "high", "critical"] as const;

export const EXPORT_FORMATS = ["txt", "json", "csv", "syslog", "cef", "leef", "evtx", "ndjson"] as const;

export const SIMULATION_MODES = [
  "Blue Team",
  "SOC",
  "Purple Team",
  "Threat Hunting",
  "CTF",
  "Empresa pequena",
  "Empresa média",
  "Banco",
  "Hospital",
  "Universidade",
  "Indústria",
  "Cloud",
  "Ransomware",
  "APT",
  "Insider Threat"
] as const;

export const COMPANY_TYPES = [
  "Empresa pequena",
  "Empresa média",
  "Banco",
  "Hospital",
  "Universidade",
  "Indústria",
  "SaaS",
  "E-commerce",
  "Governo",
  "Cloud first"
] as const;
